// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using Humanizer;
using MyIssues.DataAccess;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class IssueDetailsTableViewController : UITableViewController
	{
		public IssueDetailsTableViewController (IntPtr handle) : base (handle)
		{
		}

		Storage _storage;
		int _issueNumber;

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();

			TableView.AllowsSelection = false;
			TableView.RowHeight = UITableView.AutomaticDimension;
			TableView.EstimatedRowHeight = 40;
			TableView.SeparatorColor = UIColor.Clear;
			var controller = TabBarController as IssueTabBarViewController;
			_issueNumber = controller.IssueNumber;
			_storage = Storage.GetInstance();
			await LoadIssue();

			TableView.ReloadData();
		}

		static UIColor OpenIssueColor = UIColor.FromRGB(108, 198, 68);
		static UIColor ClosedIssueColor = UIColor.FromRGB(189,44,0);

		Octokit.Issue _issue;
		public async Task LoadIssue()
		{
			_issue = await _storage.GetIssue(_issueNumber);
			IssueNameLabel.Text = _issue.Title;
			IssueStatusView.BackgroundColor = _issue.State == Octokit.ItemState.Closed ? ClosedIssueColor : OpenIssueColor;
			IssueStatusLabel.Text = _issue.State.ToString().ApplyCase(LetterCasing.Title);
			IssueCreationDateLabel.Text = _issue.CreatedAt.Humanize();

			//LabelsView.Delegate = this;
			LabelsView.ShowsVerticalScrollIndicator = false;
			int x = 0;
			foreach (var label in _issue.Labels)
			{
				var lbl = new UILabel { 
					Font = UIFont.PreferredTitle3,
					Text = label.Name, 
					TextAlignment = UITextAlignment.Center };
				lbl.SizeToFit();
				lbl.Frame = new CoreGraphics.CGRect(x, lbl.Frame.Y, lbl.Frame.Width + 14, LabelsView.Frame.Size.Height);

				var c = Storage.LabelColors[label.Name];
				var color = UIColor.FromRGB(c[0], c[1], c[2]);

				lbl.BackgroundColor = color;
				lbl.TextColor = color.ContrastingColor();
				LabelsView.AddSubview(lbl);
				System.Diagnostics.Debug.WriteLine($"{label.Name} : {x}");
				x += (int)lbl.Frame.Size.Width;
			}
			if (_issue.Milestone != null)
			{
				IssueMilestoneCell.Hidden = false;
				if (_issue.Milestone.DueOn.HasValue)
				{
					IssueMilestoneDateLabel.Text = $"{_issue.Milestone.DueOn.GetValueOrDefault().DateTime:dd MMM}";
				}
				else 
				{
					IssueMilestoneDateLabel.Text = "--";
				}
				IssueMilestoneLabel.Text = $"{_issue.Milestone.Title}";
			}
			else 
			{
				IssueMilestoneCell.Hidden = true;
			}
			IssueBodyLabel.AttributedText = _issue.Body.FromMarkdown();
			System.Diagnostics.Debug.WriteLine(_issue.Body);

			LabelsView.ContentSize = new CoreGraphics.CGSize(x, LabelsView.Frame.Size.Height);
		}

		public override nfloat GetHeightForRow(UITableView tableView, NSIndexPath indexPath)
		{
			if (indexPath.Row == 1)
			{
				return _issue?.Milestone == null ? 0 : 30;
			}
			if (indexPath.Row == 2)
				return 30;
			if (indexPath.Row == 3)
				return 30;
				
			return UITableView.AutomaticDimension;
		}

		public override nfloat EstimatedHeight(UITableView tableView, NSIndexPath indexPath)
		{
			if (indexPath.Row == 1)
			{
				return _issue?.Milestone == null ? 0 : 30;
			}
			if (indexPath.Row == 2)
				return 30;
			if (indexPath.Row == 3)
				return 30;

			return UITableView.AutomaticDimension;
		}
	}
}
