// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MyIssues.DataAccess;
using MyIssues.Models;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class LabelsTableViewController : UITableViewController
	{

		public EventHandler<string> LabelSelected;

		struct StoryboardId
		{
			public const string LabelViewCell = "Label View Cell";
		}
		public LabelsTableViewController (IntPtr handle) : base (handle)
		{
		}

		Storage _storage;
		List<Label> _labels;

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
			_storage = Storage.GetInstance();
			_labels = await _storage.GetLabels();
			TableView.ReloadData();
		}

		public override nint NumberOfSections(UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return _labels?.Count ?? 0;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = tableView.DequeueReusableCell(StoryboardId.LabelViewCell, indexPath) as LabelViewCell;
			cell.SetLabel(_labels[indexPath.Row]);
			return cell;
		}

		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
			LabelSelected?.Invoke(this, _labels[indexPath.Row].Name);
			NavigationController.PopViewController(true);
		}
	}
}
