// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class SettingsTableViewController : UITableViewController
	{

		struct StoryboardId 
		{
			public const string SwitchRepoSegue = "Switch Repo";
		}
		public SettingsTableViewController (IntPtr handle) : base (handle)
		{
		}


		public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);


			UITapGestureRecognizer changeRepoTap = new UITapGestureRecognizer(ChangeRepoTap);
			ChangeRepoLabel.AddGestureRecognizer(changeRepoTap);
		}

		void ChangeRepoTap(UITapGestureRecognizer obj)
		{
			PerformSegue(StoryboardId.SwitchRepoSegue, this);
		}
				
	}
}
