// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Threading.Tasks;
using Foundation;
using MyIssues.DataAccess;
using MyIssues.Models;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class IssuesTableViewController : UITableViewController
	{
		public IssuesTableViewController (IntPtr handle) : base (handle)
		{
		}

		struct StoryboardId
		{
			public const string IssueCellIdentifier = "Issue Cell";
			public const string SwitchRepoSegue = "Switch Repo";
		}

		Storage _storage;
		public long RepoId
		{
			get;
			set;
		}

		public override async void ViewDidAppear(bool animated)
		{
			System.Diagnostics.Debug.WriteLine($"Attempting to load {RepoId}");
			base.ViewDidAppear(animated);
			if (RepoId == 0)
			{
				OpenRepoSelector();
			}
			else
			{
				await LoadRepo();
			}
		}

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
            _storage = Storage.GetInstance();
			if(RepoId == 0)
				RepoId = await _storage.GetWorkingRepo();
		}

		Octokit.Repository _repo;

		async Task LoadRepo()
		{
			Contract.Ensures(Contract.Result<Task>() != null);
			try
			{
				await _storage.SetWorkingRepo(RepoId);
			}
			catch (Exception e)
			{
				OpenRepoSelector();
				return;
			}
			_repo = await _storage.GetRepo(RepoId);

			Title = _repo.Name;
			//UpdateIssues(await _storage.GetIssues());
			_storage.GetIssues(UpdateIssues);

		}

		void OpenRepoSelector()
		{
			PerformSegue(StoryboardId.SwitchRepoSegue, this);
		}

		List<Issue> _issues;
		void UpdateIssues(List<Issue> issues)
		{
			System.Diagnostics.Debug.WriteLine($"Load {RepoId} ::: {(issues?.Count ?? 0)}");
			_issues = issues;
			InvokeOnMainThread(() =>
			{
				TableView.ReloadData();
			});

		}

		#region Table stuff
		public override nint NumberOfSections(UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return _issues?.Count ?? 0;
		}


		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = TableView.DequeueReusableCell(StoryboardId.IssueCellIdentifier, indexPath);

			if (cell != null)
			{
				cell.TextLabel.Text = _issues[indexPath.Row].Title;
			}

			return cell;
		}
		#endregion
	}
}
