// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class IssueDescriptionVIewController : UIViewController
	{
		public IssueDescriptionVIewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var controller = TabBarController as IssueTabBarViewController;


		}
	}
}
