// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using Humanizer;
using MyIssues.DataAccess;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class IssueDescriptionVIewController : UIViewController, IUIScrollViewDelegate
	{
		public IssueDescriptionVIewController (IntPtr handle) : base (handle)
		{
		}

		Storage _storage;
		int _issueNumber;

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
			var controller = TabBarController as IssueTabBarViewController;
			_issueNumber = controller.IssueNumber;
            _storage = Storage.GetInstance();
			await LoadIssue();
		}


		Octokit.Issue _issue;
		public async Task LoadIssue()
		{
			_issue = await _storage.GetIssue(_issueNumber);
			IssueTitleLabel.Text = _issue.Title;
			IssueStatusLabel.Text = _issue.State.ToString().ApplyCase(LetterCasing.Title);
			IssueDateLabel.Text = _issue.CreatedAt.Humanize();

			LabelsView.Delegate = this;
			LabelsView.ShowsVerticalScrollIndicator = false;
			int x = 0;
			foreach (var label in _issue.Labels)
			{
				var lbl = new UILabel { Text = label.Name }; //new UIView(new CoreGraphics.CGRect(x,0, 100,50));
				var c = Storage.LabelColors[label.Name];
				var color = UIColor.FromRGB(c[0], c[1], c[2]);
				                     
				lbl.BackgroundColor =  color;
				lbl.TextColor = color.ContrastingColor();
				x += (int)lbl.Frame.Size.Width;
			}

			IssueBodyLabel.AttributedText = _issue.Body.FromMarkdown();
			System.Diagnostics.Debug.WriteLine(_issue.Body);

			LabelsView.ContentSize = new CoreGraphics.CGSize(x,  LabelsView.Frame.Size.Height);
		}

		[Export("scrollViewDidScroll:")]
		public void Scrolled(UIScrollView scrollView)
		{
			if (scrollView.ContentOffset.Y > 0 || scrollView.ContentOffset.Y < 0)
				scrollView.ContentOffset = new CoreGraphics.CGPoint(scrollView.ContentOffset.X, 0);
		}

		/*
		for (int i = 0; i < 8; i++) {
            UIButton *button = [[UIButton alloc] initWithFrame:CGRectMake(x, 0, 100, 100)];
            [button setTitle:[NSString stringWithFormat:@"Button %d", i] forState:UIControlStateNormal];

            [scrollView addSubview:button];

            x += button.frame.size.width;
        }

        scrollView.contentSize = CGSizeMake(x, scrollView.frame.size.height);
            scrollView.backgroundColor = [UIColor redColor];

		*/
	}
}
