// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using MyIssues.DataAccess;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class IssueDescriptionVIewController : UIViewController
	{
		public IssueDescriptionVIewController (IntPtr handle) : base (handle)
		{
		}

		Storage _storage;
		int _issueNumber;

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
			var controller = TabBarController as IssueTabBarViewController;
			_issueNumber = controller.IssueNumber;
            _storage = Storage.GetInstance();
			await LoadIssue();
		}


		Octokit.Issue _issue;
		public async Task LoadIssue()
		{
			_issue = await _storage.GetIssue(_issueNumber);
			IssueTitleLabel.Text = _issue.Title;
			IssueStatusLabel.Text = _issue.State.ToString();
			IssueDetailLabel.Text = _issue.CreatedAt.ToString();
		}
	}
}
