// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class PreviewReplyViewController : UIViewController
	{
		public PreviewReplyViewController (IntPtr handle) : base (handle)
		{
		}

		public string  Content
		{
			get;
			set;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			NavBar.RightBarButtonItem.Clicked += (sender, e) => Cancel();
			ContentLabel.AttributedText = Content.FromMarkdown();
			ContentLabel.SizeToFit();
		}

		void Cancel()
		{
			PresentingViewController.DismissModalViewController(true);
		}
	}
}
