// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Threading.Tasks;
using Foundation;
using MyIssues.DataAccess;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class ReplyToIssueViewController : UIViewController
	{
		public ReplyToIssueViewController (IntPtr handle) : base (handle)
		{
		}

		int _issueNumber;
		public void SetIssueNumber(int number)
		{
			_issueNumber = number;
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			NavBar.Title = $"Reply to #{_issueNumber}";
			NavBar.LeftBarButtonItem.Clicked += (sender, e) => Cancel();
			NavBar.RightBarButtonItem.Clicked += async (sender, e) => 
			{
				var b = await Reply();
				Cancel();
			};
		}

		 void Cancel()
		{
			PresentingViewController.DismissModalViewController(true);
			//NavigationController.PopViewController(true);
		}

		async Task<bool> Reply()
		{

			return await Storage.GetInstance().SendComment(_issueNumber, ReplyTextView.Text);
		}
	}
}
