// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class ReplyToIssueViewController : UIViewController
	{
		public ReplyToIssueViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
