// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using MyIssues.Models;
using UIKit;

namespace MyIssues2.iOS.Cells
{
	public partial class IssueCellView : UITableViewCell
	{
		public IssueCellView (IntPtr handle) : base (handle)
		{
		}

		public void SetIssueTitle(string title)
		{
			IssueTitleLabel.Text = title;
		}

		public void SetColors()
		{
		}

		internal void SetColors(IReadOnlyList<Label> labels)
		{
			if (labels.Count > 0)
				LabelColorView1.BackgroundColor = UIColor.FromRGB(labels[0].R, labels[0].G, labels[0].B);
			if (labels.Count > 1)
				LabelColorView2.BackgroundColor = UIColor.FromRGB(labels[1].R, labels[1].G, labels[1].B);
			if (labels.Count > 2)
				LabelColorView3.BackgroundColor = UIColor.FromRGB(labels[2].R, labels[2].G, labels[2].B);
			if (labels.Count > 3)
				LabelColorView3.BackgroundColor = UIColor.FromRGB(labels[3].R, labels[3].G, labels[3].B);
			if (labels.Count > 4)
				LabelColorView3.BackgroundColor = UIColor.FromRGB(labels[4].R, labels[4].G, labels[4].B);
		}
	}
}
