// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS
{
	public partial class LabelViewCell : UITableViewCell
	{
		public LabelViewCell (IntPtr handle) : base (handle)
		{

		}

		public void SetLabel(MyIssues.Models.Label label)
		{
			ContentView.BackgroundColor = UIColor.FromRGB(label.R, label.G, label.B);
		}
	}
}
