// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MyIssues2.iOS.Cells
{
	public partial class RepoViewCell : UITableViewCell
	{
		public RepoViewCell (IntPtr handle) : base (handle)
		{
		}

		public void SetRepo(MyIssues.Models.Repository repository)
		{
			OwnerLabel.Text = repository.Owner;
			RepoNameLabel.Text = repository.Name;
			LanguageLabel.Text = repository.Language;
			DescriptionLabel.Text = repository.Description;
		}
	}
}
